### ISSUE TITLE
Support Pipfile

### ISSUE THREAD

**Issue by anseljh** [fossas/fossa-cli#132]
[Pipenv](https://docs.pipenv.org/) is the latest and greatest in Python packaging, and it uses a new file called `Pipfile` instead of `requirements.txt`.

More on `Pipfile`: https://github.com/pypa/pipfile

**Comment by ilikebits** [comment]
We're planning a refactor of how builders work to better support multiple strategies per ecosystem, and Pipfile support will probably come in afterwards. That said, I'd be happy to review a PR for this and merge it in afterwards.

**Comment by zlav** [comment]
Support for Pipenv has been added, however fossa will not automatically detect a project using Pipenv. In order to analyze a Pipenv project, set the corresponding module type in your fossa config file, `.fossa.yml`, to Pipenv:
```analyze:
  modules:
  - name: fossa
    path: ./cmd/fossa
    type: pipenv
```

Issue [#351] is dedicated to improving the detection of Pipenv projects.
