### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wood4099** [fossas/fossa-cli#1430]
**Important:** Bug reports should be directed to `support@fossa.com` for faster response and prioritization. Bug reports may still be created here but they may not get immediate attention and may be closed in favor of internally tracked tickets.

**Describe the bug**
Analyze the winui3 c # project using Fossa and execute the command "Fossa analyze -- experimental enable binary discovery -- force vendor dependency scan method ArchiveUpload -- debug". However, the Fossa website did not scan all TRANSITIVE DEPENDENCIES.

**To Reproduce**

**Expected behavior**
The system *. of Deep dependencies Dll scans very few surfaces and does not correspond to the ones used in the program.

**Debug bundle**
[fossa.debug.json.gz](https://github.com/fossas/fossa-cli/files/15338562/fossa.debug.json.gz)

**Additional context**
![image](https://github.com/fossas/fossa-cli/assets/3077273/896d19b0-8b1f-472f-bfe1-a25233b791c7)

**Comment by jssblck** [comment]
Hey there @wood4099!

Thanks for this issue- it looks like this is going to require some specific details from you around your project, in particular details around the reason for why you believe the reported list to be invalid.

Please open a ticket on our support site so that we can discuss this in more detail! I'm going to close the ticket here but please do follow up through the support site.
