### ISSUE TITLE
Improve automatically-assigned project name

### ISSUE THREAD

**Issue by xizhao** [fossas/fossa-cli#212]
Current project name is the git endpoint when uploaded to FOSSA

This is confusing and ugly, we should just use the project title or end of the URL.

**Comment by ilikebits** [comment]
I'm not sure what you mean by "project title". We already allow users to specify titles by flag or configuration file (see https://github.com/fossas/fossa-cli/blob/d41a95261bf208746384b96ed298245a4effec6f/api/fossa/upload.go#L53). If you mean something like the `name` in a `package.json`, not all projects have a single well-defined name, because they're composed of multiple modules.

**Comment by zlav** [comment]
Closing due to uncertain acceptance criteria. Project names including git endpoint are used in the cli because they are expected by the FOSSA api endpoints in order to associate github projects.
