### ISSUE TITLE
Please provide docker image with just fossa cli

### ISSUE THREAD

**Issue by mmlb** [fossas/fossa-cli#243]
**Is your feature request related to a problem? Please describe.**
I'm looking to run fossa with the "Provided Builds" option. We use droneci as our ci provider and would like to use a docker image maintained by this project if possible. But the image is huge, especially when all I need is the fossa binary.

**Describe the solution you'd like**
Build fossa statically, then COPY the binary into a minimal image (alpine:latest imo).

**Describe alternatives you've considered**
Doing ^ myself.

**Additional context**
I'm pretty new to fossa and fossa-cli and am assuming that when using the "Provided Builds" option the only requirement is the `fossa` binary. Is that correct?

**Comment by liftM** [comment]
The Docker image is primarily used for development and testing. The CLI is intended to be run inside your regular build container, since it queries those tools for build information.

There would be no point in running a separate FOSSA CLI image, because its copy of Maven (or whatever your particular build tool is) would not be the copy of Maven used to build your program, which means we would not be able to get the correct build data.

If you want an easy method for adding the CLI into your own image, you can use `curl https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash`

**Comment by mmlb** [comment]
Hi @liftM. Your response brings up a question I had while messing with this yesterday. It seems the fossa binary is trying to rebuild my go binary. I presume in order to gather info on the build. I could not find such information in any of the docs, especially not anything clearly. The docs read to me like fossa will parse deps/vendor files from the source directory and/or parse info from the already-built-binary. I think making this more obvious in the docs (usage and how-it-works) would be helpful.

**Comment by liftM** [comment]
Thanks, improving documentation is something we're working on.

To be clear, `fossa` does not rebuild your binary. It only runs `go list`, to get the Go compiler's view of the source packages (this is more complex than just reading the filesystem, because of things like `internal` package directories, build tags, non-vendored dependencies, etc.).
