### ISSUE TITLE
Better installation methods

### ISSUE THREAD

**Issue by liftM** [fossas/fossa-cli#32]
Some ideas:

- [x] Install script for `curl | bash` or other one-liner. We can probably take the script from jpillora/installer.
- [ ] `npm install -g @fossa/cli`
- [ ] `brew install @fossa/cli`

Some references:

- https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8

**Comment by xizhao** [comment]
merging #35 as duplicate

**Comment by xizhao** [comment]
Currently, one liner using jpillora/installer 

```bash
curl https://i.jpillora.com/fossas/fossa-cli! | bash && mv /usr/local/bin/fossa-cli /usr/local/bin/fossa
```

**Comment by ilikebits** [comment]
We have an installer script now, but there are some improvements we can make:

1. Automatically pull the latest stable version instead of a hardcoded version (probably by querying the Releases API)
2. Figure out a way to validate the checksum on Mac OS (apparently `sha256sum` is not installed by default?)
3. Install to a location other than `/usr/bin` to avoid requiring `sudo` permissions for most users (maybe install to `.fossa`, append it to the `$PATH`, and provide a `.bashrc` `EXPORT PATH=$PATH:$HOME/.fossa` line?)

**Comment by liftM** [comment]
Our current installer satisfies these requirements pretty well.
