### ISSUE TITLE
Raw modules require API key even for `analyze --output`

### ISSUE THREAD

**Issue by liftM** [fossas/fossa-cli#348]
Raw module support is currently a gigantic hack within `cmd/analyze`. Right now, it tries to do an upload even when `--output` is passed. This causes analyses with raw modules to fail.

Ideally, we would refactor raw modules (possibly into their own analyser). At the very least, we should avoid uploading on `--output`.

**Comment by microsoftly** [comment]
I'm not sure we'll be able to get around this 100%. If the user provides an revision, then we can properly generate the locator for the `tarball`. If they do not provide one, we default to using the md5 hash of the `tarball`, which requires an upload. 

Either way, we require the `orgId` in order to properly generate the locator. 

When `--output` is used, we could potentially stub out or do a best guess at the projectName or revision for the upload. Generally speaking, those that are looking at the output of `--output` are looking at the dep graph and likely do not care about the locator of the module (at least that's my understanding)

**Comment by liftM** [comment]
> When --output is used, we could potentially stub out or do a best guess at the projectName or revision for the upload. 

We don't do an upload on `--output`. The easy fix here is to just turn off that code path when we know we're not doing an upload.

> Generally speaking, those that are looking at the output of --output are looking at the dep graph and likely do not care about the locator of the module (at least that's my understanding)

Yup. Let's just ignore the tarball.

**Comment by zlav** [comment]
Addressed in PR #416

**Comment by zlav** [comment]
Reopening, PR #416 addressed part of this issue and provides a better route to the solution.
