### ISSUE TITLE
Add support for darwin/arm64 platform

### ISSUE THREAD

**Issue by simonseyer** [fossas/fossa-cli#679]
When executing the latest `install.sh`, the following error is presented:

```
fossas/fossa-cli crit platform darwin/arm64 is not supported.  Make sure this script is up-to-date and file request at https://github.com/fossas/fossa-cli/issues/new
```

We are running our iOS builds on Mac Mini machines with Apple Silicon processor. In order for our FOSSA integration to work we need support for arm64 on macOS. 

I assume that more and more iOS build machines will transition to arm processors making this a generally useful feature for a wide range of users.

**Comment by scruffystuffs** [comment]
Thanks for the report!  This project is actually in maintenance mode currently, and all future work is happening on https://github.com/fossas/spectrometer (a.k.a. `fossa-cli v2`).  We don't yet natively support the M1 chip yet (in either tool), but we do have a workaround that allows you to install and run.

Due to this project being in maintenance mode, and soon to be deprecated entirely, we're not going to fix this here.  However, once the upstream properly supports it, we're going to include _native_ support for the M1 in our new tool, rather than just a workaround.

I'm going to close this, since we won't be fixing this issue here.

**Comment by simonseyer** [comment]
Ah, I wasn't aware that you are working on a successor. Good to know 👌 Out of curiosity: what will be the benefits of the new tool? I've also checked out the workaround and that should work for us for now.

**Comment by scruffystuffs** [comment]
Main benefit is that the config file is no longer required.  Many repositories will be able to run with nothing more than:
```shell
FOSSA_API_KEY=xxxx
fossa analyze
```

**Comment by henry2man** [comment]
> Thanks for the report! This project is actually in maintenance mode currently, and all future work is happening on https://github.com/fossas/spectrometer (a.k.a. `fossa-cli v2`). We don't yet natively support the M1 chip yet (in either tool), but we do have a workaround that allows you to install and run.

Just a comment for those who come here through Google: Finally Spectometer has merged into fossa-cli and the live issue on this problem is #662
