### ISSUE TITLE
Fossa generate two different hash value for same dependency file

### ISSUE THREAD

**Issue by ShengYanMei** [fossas/fossa-cli#709]
Hi owners:
I have problem on detecting existing licenses in my analyze project.

I have a dependency file locate at a specific directory, and there is license file in the same directory,  so I added this file as a vendored-dependency:

vendored-dependencies:
  - name: Packages/com.xxx/Runtime/xxx/Plugins/xx.dll
    path: Packages/com.xxx/Runtime/xxx/Plugins/xx.dll
    version: x.x

and in my yml file, target be like:

paths:
  only:
    - ./Packages/com.xxx

Then analyze result turned to generate two different hash values for the only file.
![image](https://user-images.githubusercontent.com/20438862/142611516-7108d57b-1b71-41a9-9aa8-02d083fd8d3d.png)
Then it reports one file without license, but there is only one dependency file, does anyone know how to resolve this? 
A report that I expect is there is no unlicensed file in this directory, since I have the license.

**Comment by ShengYanMei** [comment]
Hi @meghfossa, I'd prefer you could help me with this issue first, since issue #698 has a workaround, this issue is the main issue that blocks my work now, really appreciate your help.thx.

**Comment by meghfossa** [comment]
Hi @ShengYanMei - Since this touches FOSSA web application, I recommend you open a support ticket via email at support@fossa.com, who can help you with this. 

When you do open a support ticket, please provide them:

- Your Project Url
- Your Cli version (`fossa --version`)
- Cli debug logs (you can generate them by using `--debug` flag, it shall create `fossa.debug.json.gz`)

**Comment by zlav** [comment]
@ShengYanMei I am going to close this ticket in favor of you opening one with support@fossa.com if you have not already.
