### ISSUE TITLE
Ambiguous error message when provided builds is disabled

### ISSUE THREAD

**Issue by alvin-huang** [fossas/fossa-cli#72]
When pushing provided builds to FOSSA, if the `enable provided builds` checkbox is not checked, fossa-cli gives me:
```
CRITICAL Upload failed: bad server response ("\"This project is not configured to accept Provided Builds. Set `require_mediated_dependencies` to `true` in order to enable\"")
```
However, this is not exactly true. Once you check the checkbox for `enable provided builds` it will allow you to push without having to check the box for `prefer mediated data`. Should these two settings be turned on and off together?

**Comment by ilikebits** [comment]
Yes, that's correct. This is an issue we'll need to resolve on our backend, but thanks for reporting this! We'll keep the issue in this repository updated.

In general, we need better error messages. This is mostly blocked on improving error handling on the backend API.

**Comment by xizhao** [comment]
Agreed. For clarity:

 - `require_mediated_dependencies` is our backend flag for enabling provided builds 
 - `prefer_mediated_data` is a flag for our automated build infrastructure (hosted) to run dynamic analysis instead of static analysis for your dependencies

The solution is to improve our error messages on the backend route.  Keeping this open until we resolve it on our side.

**Comment by zlav** [comment]
Closing due to the issue no longer being relevant.
