### ISSUE TITLE
Fossa-cli Github build and dependency scan badges show as "failing"

### ISSUE THREAD

**Issue by PenelopeFudd** [fossas/fossa-cli#796]
Hi;

I'm not a user, I just saw a link to Fossa-cli in the Logstash source and thought I'd see what Fossa is.

Sorry to have to report that the badges in the Readme.md file are failing:

* ![https://github.com/fossas/fossa-cli/actions/workflows/build.yml/badge.svg](https://github.com/fossas/fossa-cli/actions/workflows/build.yml/badge.svg)
* ![https://github.com/fossas/fossa-cli/actions/workflows/dependency-scan.yml/badge.svg](https://github.com/fossas/fossa-cli/actions/workflows/dependency-scan.yml/badge.svg)

**Comment by scruffystuffs** [comment]
Thanks for the report.  We do already have fixes for these two issues:
- Dependency Scan has been merged, but it won't take effect until the next release, which will likely be within the week
- Build was introduce as a merge conflict, and we have an open PR ready to fix it.

Since there's no real followup action here, other than what we're already doing, I'm going to close this.  You should see both badges report passing within the week.
